In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
x.ndim

1

In [4]:
x.shape

(6,)

In [5]:
x.size

6

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
A.size

9

In [10]:
A.shape

(3, 3)

# Zmiana wymiaru

In [13]:
x.shape = (2,3)

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
B = A.reshape(1,9)
B

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
x.reshape(6,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [24]:
A.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Typy danych

In [25]:
A.dtype

dtype('int64')

In [26]:
x.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

In [27]:
x.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
np.array(['napis', 5, 6+3j, 5.6, True])

array(['napis', '5', '(6+3j)', '5.6', 'True'], dtype='<U6')

In [31]:
np.array([5, 6+3j, 5.6, True])

array([5. +0.j, 6. +3.j, 5.6+0.j, 1. +0.j])

In [33]:
np.arange(1,5,2)

array([1, 3])

In [34]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(12,-5,-1, dtype=float)

array([12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.,
       -1., -2., -3., -4.])

In [38]:
np.arange(12,-5,-1, dtype=complex)

array([12.+0.j, 11.+0.j, 10.+0.j,  9.+0.j,  8.+0.j,  7.+0.j,  6.+0.j,
        5.+0.j,  4.+0.j,  3.+0.j,  2.+0.j,  1.+0.j,  0.+0.j, -1.+0.j,
       -2.+0.j, -3.+0.j, -4.+0.j])

In [39]:
##LINSPACE

In [40]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
np.linspace(0,1,5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [43]:
np.r_[1:13:2]

array([ 1,  3,  5,  7,  9, 11])

In [44]:
np.r_[0:1:5j]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## macierzowe

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [48]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.empty((5,7))

array([[4.68512862e-310, 4.68512862e-310, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322, 5.53353523e-322,
        0.00000000e+000],
       [3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.78734488e-051, 4.04461962e-037,
        8.39356298e+165],
       [2.57078568e+184, 1.40802568e-075, 7.86377741e-067,
        2.03840611e+184, 2.14788035e+184, 1.63041663e-322,
        4.68512862e-310],
       [4.68512862e-310, 1.34385856e-321, 2.37151510e-322,
        0.00000000e+000, 4.94065646e-324, 0.00000000e+000,
        0.00000000e+000],
       [1.48219694e-322, 4.00193173e-322, 4.68512862e-310,
        4.68512844e-310, 4.62445445e-321, 4.44659081e-323,
        6.92263259e-310]])

In [56]:
np.random.uniform(-4,4,10)

array([-2.96803405, -1.93193895, -0.73457021,  0.1339629 ,  1.58673981,
       -2.44815597,  1.09740286,  0.43268309, -3.35234128,  3.52070972])

In [57]:
np.random.uniform(low=-4, high=4, size=(3,4))

array([[-2.39340054, -0.56137454, -0.07664921,  2.81263387],
       [ 0.06231264, -0.54370933,  0.06103002,  2.31638622],
       [ 0.88000137, -0.47714135, -1.19860735,  2.17983211]])

In [58]:
np.random.normal(loc=1.75, scale=0.5, size=10)

array([1.865035  , 1.87869736, 1.54024709, 1.98697116, 1.24705349,
       2.0116885 , 1.9614964 , 1.88782691, 3.15869639, 1.66278155])

In [59]:
np.random.normal(loc=1.75, scale=0.05, size=10)

array([1.74494437, 1.74369116, 1.74875815, 1.7191925 , 1.76839539,
       1.71494488, 1.76286354, 1.73977623, 1.77260857, 1.7636607 ])

In [61]:
np.random.randint(2,10,(2,8))

array([[2, 9, 4, 7, 4, 6, 5, 8],
       [4, 2, 7, 4, 4, 8, 9, 5]])

In [62]:
np.random.choice(['Pies','Kot','Mysz'], 5)

array(['Pies', 'Kot', 'Kot', 'Kot', 'Mysz'], dtype='<U4')

In [64]:
np.random.choice(['Pies','Kot','Mysz'], 3, replace=False)

array(['Mysz', 'Kot', 'Pies'], dtype='<U4')

In [66]:
np.random.choice(['Pies','Kot','Mysz'], 10, p=[0.5,0.25,0.25])

array(['Pies', 'Pies', 'Pies', 'Mysz', 'Mysz', 'Pies', 'Pies', 'Pies',
       'Kot', 'Pies'], dtype='<U4')

In [67]:
np.repeat(5,6)

array([5, 5, 5, 5, 5, 5])

In [68]:
np.repeat((1,2),5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [69]:
np.repeat([1,2],[2,4])

array([1, 1, 2, 2, 2, 2])

In [70]:
np.tile([1,2], 4)

array([1, 2, 1, 2, 1, 2, 1, 2])

In [71]:
np.tile([1,2], [4,2])

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [72]:
# a

In [73]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.r_[x,y]

array([1, 2, 3, 4, 5, 6])

In [75]:
np.vstack((A,[100,99,98]))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100,  99,  98]])

In [77]:
np.hstack((A,[[100],[99],[98]]))

array([[  1,   2,   3, 100],
       [  4,   5,   6,  99],
       [  7,   8,   9,  98]])

In [80]:
w = np.array([100,99,98])
w.reshape((1,3))
np.hstack((A,w))

ValueError: all the input arrays must have same number of dimensions

In [81]:
np.insert(A, 2,[100,99,98], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,  99,  98],
       [  7,   8,   9]])

In [82]:
np.r_[1,23,3]

array([ 1, 23,  3])

In [83]:
np.r_[1,2,3] + np.r_[4,5,6]

array([5, 7, 9])

In [89]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[1,2,3],[100,101,102]])
x2 + y2

array([[  2,   4,   6],
       [104, 106, 108]])

In [90]:
np.r_[1,2,3] +10

array([11, 12, 13])

In [92]:
2 ** np.arange(0,11)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [93]:
np.max(x2)

6

In [94]:
x2 > y2

array([[False, False, False],
       [False, False, False]])

In [96]:
1 != np.eye(4,4)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [104]:
x >1

array([False,  True,  True])

In [103]:
y > 5

array([False, False,  True])

In [105]:
(x >1) & (y > 5)

array([False, False,  True])

In [107]:
(x >1) | (y > 5)

array([False,  True,  True])

In [109]:
~ (y > 5)

array([ True,  True, False])

In [110]:
np.all(~ (y > 5))

False

In [112]:
np.all([True, True, True])

True

In [113]:
np.any(~ (y > 5))

True

In [114]:
np.sum(~ (y > 5))

2

# NaN

In [116]:
nanwek = np.array([1,np.NaN, 3])
nanwek

array([ 1., nan,  3.])

In [117]:
np.nansum(nanwek)

4.0

In [118]:
np.isnan(nanwek)

array([False,  True, False])

In [119]:
np.sort(nanwek)

array([ 1.,  3., nan])

In [120]:
x

array([1, 2, 3])

In [121]:
x[-1]

3

In [122]:
x[0:1]

array([1])

In [123]:
x[:2]

array([1, 2])

In [124]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
x2[1]

array([4, 5, 6])

In [126]:
x2[1:2]

array([[4, 5, 6]])

In [134]:
x2[0:1][0]

array([1, 2, 3])

In [135]:
x

array([1, 2, 3])

In [136]:
x3 = x[1:].copy()

In [137]:
x[(y > 5)]

array([3])

In [138]:
x[[1,0,1,2,2,0,0,1,0,2]]

array([2, 1, 2, 3, 3, 1, 1, 2, 1, 3])

In [139]:
np.where(x == 3)

(array([2]),)

In [141]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.where(x2 == 2)

(array([0]), array([1]))

In [143]:
np.where(x2 == 2, 4, 8)

array([[8, 4, 8],
       [8, 8, 8]])